@startuml

skinparam classAttributeIconSize 0
skinparam shadowing false

class CallbackHandler {
  {static} +ctorCallback(args: FunctionCallbackInfo<Value>)

  {static} +memberGetterCallback(property: Local<String>, info: PropertyCallbackInfo<Value>)
  {static} +memberSetterCallback(property: Local<String>, value: Local<Value>, info: PropertyCallbackInfo<Value>)
  {static} +memberFunctionCallback(args: FunctionCallbackInfo<Value>)

  {static} +staticGetterCallback(property: Local<String>, info: PropertyCallbackInfo<Value>)
  {static} +staticSetterCallback(property: Local<String>, value: Local<Value>, info: PropertyCallbackInfo<Value>)
  {static} +staticFunctionCallback(args: FunctionCallbackInfo<Value>)

}


@enduml
