@startuml

skinparam classAttributeIconSize 0
skinparam shadowing false

class ObjectProxy {
  #proxy: Persistent<Object>
  --
  +ObjectProxy(type: TDataMember, scope: TClassRef) <<constructor>>
  +getType(): TDataMember

  {abstract} +set(value: ObjectProxy)
  {abstract} +get(): Local<Value>

  {abstract} +setProxy(proxy: Local<Object>)
  {abstract} +getProxy(): Local<Object>

  {abstract} +isPrimitive(): bool
}

@enduml
