@startuml

!include ./config/diagramsConfig.puml
!include ./config/classConfig.puml

title: createProxyFunction
[-> FunctionProxyFactory
activate FunctionProxyFactory
FunctionProxyFactory -> FunctionProxy: getCallFunc()
activate FunctionProxy
FunctionProxy -> cling
ref over cling: cling internals
cling -> FunctionProxy: <<pointer to ROOT function>>
deactivate FunctionProxy
FunctionProxy -> FunctionProxyFactory:
deactivate FunctionProxyFactory
FunctionProxyFactory ->[: <<pointer to ROOT function>>

@enduml
