@startuml

!include ./config/diagramsConfig.puml
!include ./config/sequenceConfig.puml

title rootJS initialization sequence

actor "Client Application" as Client
participant "NodeApplication" as NodeApp
participant "<u>instance:NodeApplication</u>" as Instance
participant "<u>:Node</u>" as V8

activate Client
Client -> V8: require(rootJS.node)

activate V8
V8 ->> NodeApp : <u>Initialize(exports, module)</u>
deactivate V8

activate NodeApp

/' set exit hook '/
NodeApp -> V8 : AtExit(Exit)
activate V8
V8 --> NodeApp
deactivate V8

/' instance creation '/
NodeApp -> NodeApp : <u>Instance()</u>
activate NodeApp
alt not initialized
  create Instance
  NodeApp --> Instance : <<create>>
end
NodeApp --> NodeApp : instance
deactivate NodeApp

/' init ROOT environment '/
NodeApp -> Instance : initROOTGlobals()
activate Instance
Instance --> NodeApp
deactivate Instance

NodeApp -> Instance : initROOTMessageCallback()
activate Instance
Instance --> NodeApp
deactivate Instance

/' Exposure of ROOT'/
NodeApp -> Instance : exposeROOT()
activate Instance
Instance --> NodeApp
deactivate Instance

NodeApp --> Client: exports
deactivate NodeApp

deactivate Client
@enduml
